[package]
name = "softbuffer-rgb"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-window-handle = "0.6.2"
softbuffer = "0.4.5"

[dev-dependencies]
winit = "0.30.4"

[[test]]
name = "test"
path = "tests/test.rs"
harness = false
